import { create } from 'zustand'

const useStore = create((set, get) => ({
  scrollProgress: 0,
  scrollVelocity: 0,
  mouseX: 0,
  mouseY: 0,
  mouseNormalX: 0,
  mouseNormalY: 0,
  activeFirefly: null,
  showPaper: false,
  paperContent: null,
  soundEnabled: false,
  soundGateDismissed: false,
  entryComplete: false,
  minigameActive: false,
  minigameEnded: false,
  caughtJokes: [],
  jarVisible: false,
  foxState: 'idle',
  isNight: false,
  windGust: 0,
  windTime: 0,
  performance: { lowPower: false, isMobile: false },

  setScrollProgress: (v) => set({ scrollProgress: v }),
  setScrollVelocity: (v) => set({ scrollVelocity: v }),
  setMouse: (x, y, nx, ny) => set({ mouseX: x, mouseY: y, mouseNormalX: nx, mouseNormalY: ny }),
  openPaper: (content) => set({ showPaper: true, paperContent: content, activeFirefly: content.id }),
  closePaper: () => set({ showPaper: false, paperContent: null, activeFirefly: null }),
  setSoundEnabled: (v) => set({ soundEnabled: v }),
  dismissSoundGate: () => set({ soundGateDismissed: true }),
  completeEntry: () => set({ entryComplete: true }),
  setMinigameActive: (v) => set({ minigameActive: v }),
  endMinigame: () => set({ minigameEnded: true, minigameActive: false }),
  catchJoke: (joke) => set((s) => ({ caughtJokes: [...s.caughtJokes, joke] })),
  showJar: () => set({ jarVisible: true }),
  hideJar: () => set({ jarVisible: false }),
  setFoxState: (v) => set({ foxState: v }),
  setWind: (gust, time) => set({ windGust: gust, windTime: time }),
  setPerformance: (p) => set({ performance: p }),
  setNight: (v) => set({ isNight: v }),
}))

export default useStore
